"""Fail-closed independent-provenance gate for the fixed Phase 3P.3 pool."""
from __future__ import annotations
import json,sys
from collections import Counter
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
P3=ROOT/'artifacts/training/phase3p/phase3p3_sar_native_supervision';OUT=ROOT/'artifacts/training/phase3p/phase3p4_sar_water_provenance_audit'
REQUIRED=('record_id','s1_patch_identity','phase3p3_label','independent_evidence_source','independent_water_fraction','spatial_alignment_result','audit_decision','confidence','agreement_with_phase3p3_label','reason','provenance')
def dump(n,x):(OUT/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n',encoding='utf8')
def valid_schema(r):return set(REQUIRED)<=set(r)
def main():
 if OUT.exists():raise RuntimeError('PHASE3P4_NAMESPACE_EXISTS')
 OUT.mkdir(parents=True);pool=json.loads((P3/'phase3p3_candidate_pool.json').read_text())['records'];assert len(pool)==100 and Counter(r['answer'] for r in pool)=={'yes':50,'no':50}
 protocol={'phase':'3P.4','pool_source':str(P3/'phase3p3_candidate_pool.json'),'identity_reuse_required':True,'independent_evidence_definition':'A patch-aligned water reference with provenance independent of BigEarthNet CLC2018/reBEN labels. BigEarthNet Reference_Maps are excluded because they are the dataset reference-map/target lineage, not an independent source.','spatial_alignment_rule':{'required':['CRS equality','patch-bounds equality','grid/extent overlap','valid finite reference pixels'],'fail_closed':True},'pre_registered_water_fraction_rule':{'water_present_confirmed':'independent water fraction >= 0.05','water_absent_confirmed':'independent water fraction <= 0.01','ambiguous':'0.01 < fraction < 0.05','no_reference':'UNVERIFIABLE'},'readiness_gate':{'minimum_confirmed_total':60,'minimum_confirmed_train_per_class':20,'minimum_confirmed_validation_per_class':5,'minimum_agreement_fraction':0.95,'required':['independent evidence for every retained record','verified spatial alignment','complete provenance','opposite-label confirmed shuffle pairs','zero TEST access'],'classification_if_failed':'SAR_WATER_POOL_NEEDS_MORE_PROVENANCE'},'no_training':True,'test_access_count':0}
 dump('phase3p4_audit_protocol.json',protocol);print('PHASE3P4 START\nCANDIDATES = 100\nINDEPENDENT REFERENCE SOURCE = NONE_FOUND; BigEarthNet Reference_Maps rejected as non-independent CLC lineage\nAUDIT RULE = '+json.dumps(protocol['pre_registered_water_fraction_rule'],sort_keys=True),flush=True)
 records=[]
 for i,r in enumerate(pool,1):
  print(f'[3P4][AUDIT] record {i}/100',flush=True)
  records.append({'record_id':r['record_id'],'s1_patch_identity':r['sentinel1_patch_id'],'phase3p3_label':r['answer'],'independent_evidence_source':None,'independent_water_fraction':None,'spatial_alignment_result':'NOT_APPLICABLE_NO_INDEPENDENT_REFERENCE','audit_decision':'UNVERIFIABLE','confidence':'NONE','agreement_with_phase3p3_label':None,'reason':'No independently sourced, patch-aligned water reference or documented human audit is available locally. The BigEarthNet Reference_Maps share the CLC-derived target lineage and are rejected to avoid circular validation.','provenance':{'phase3p3_record_id':r['record_id'],'phase3p3_source':r['authoritative_source'],'rejected_nonindependent_source':'BigEarthNet Reference_Maps / CLC target lineage'},'test_access_count':0})
 assert all(valid_schema(r) for r in records)
 agreement={'records_audited':len(records),'confirmed_water':0,'confirmed_non_water':0,'ambiguous':0,'unverifiable':len(records),'original_yes_independently_yes':0,'original_yes_independently_no':0,'original_no_independently_no':0,'original_no_independently_yes':0,'agreement_fraction':None,'agreement_reason':'No independent decisions exist; agreement is intentionally not computed.','test_access_count':0}
 split={'train':{'confirmed_yes':0,'confirmed_no':0},'validation':{'confirmed_yes':0,'confirmed_no':0}}
 summary={'status':'PHASE3P4_BLOCKED_NO_INDEPENDENT_REFERENCE','independent_reference_source':'NONE_FOUND','candidate_identity_reused_exactly':True,'records_audited':100,'agreement':agreement,'confirmed_split_distribution':split,'spatial_alignment':'NOT_PERFORMED: no independent geospatial reference exists; all candidates fail closed','sar_statistical_sanity':'NOT_COMPUTABLE_FOR_CONFIRMED_GROUPS: confirmed groups are empty; Phase 3P.3 statistics are not substituted as ground truth','valid_opposite_label_shuffle_pairs':0,'test_access_count':0,'pool_classification':'SAR_WATER_POOL_NEEDS_MORE_PROVENANCE','bounded_standalone_sar_retraining_justified':False,'confirmed_manifests_created':False,'controller_routing':'BLOCKED','fusion':'BLOCKED','recommendation':'Obtain a separately sourced, patch-aligned water reference (or documented independent manual review with supporting reference) for each candidate; then rerun this exact immutable audit protocol.'}
 dump('phase3p4_record_audit.json',{'records':records,'test_access_count':0});dump('phase3p4_agreement_summary.json',agreement);dump('phase3p4_summary.json',summary)
 print('CONFIRMED WATER = 0\nCONFIRMED NON-WATER = 0\nAMBIGUOUS = 0\nUNVERIFIABLE = 100\nORIGINAL-vs-INDEPENDENT AGREEMENT = NOT_COMPUTABLE\nTRAIN CONFIRMED = 0\nVALIDATION CONFIRMED = 0\nSHUFFLE PAIRS STILL VALID = 0\nTEST ACCESS = 0\nPOOL CLASSIFICATION = SAR_WATER_POOL_NEEDS_MORE_PROVENANCE',flush=True)
if __name__=='__main__':main()
