"""Final SatQuery v1 paired S1+S2 end-to-end integration validation."""
from __future__ import annotations
import json,os,sys,time
from collections import Counter
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from src.dataset_loader import discover_samples,load_sample
from src.eo_vlm.optical_sar_joint import EXPECTED_JOINT_FINGERPRINT,EXPECTED_JOINT_SHA,module_fingerprint
from src.eo_vlm.sar_projector import S1SARProjector
from src.eo_vlm.multispectral_projector import S2MultispectralProjector
from src.satquery_v1 import SatQueryV1Controller,JOINT
OUT=ROOT/'artifacts/final/satquery_v1';SOURCE=ROOT/'artifacts/training/phase3q/phase3q1_fusion_adaptation';MANIFEST=SOURCE/'phase3q1_training_manifest.json';DATA=Path(r'D:\Satquery_ai datasets\comparison\raw-1000');S1CK=ROOT/'artifacts/training/phase3p/phase3p1_sar_adaptation/phase3p1_sar_projector_final.pt';S2CK=ROOT/'artifacts/training/phase3o/phase3o12_run/phase3o12_projector_final.pt'
def dump(n,x):(OUT/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
def q(r):return 'Describe this paired Sentinel-1 and Sentinel-2 scene.' if r['task_type']=='caption' else r['question']
def a(r):return r['caption'] if r['task_type']=='caption' else r['answer']
def ram():
 try:
  import psutil;return psutil.Process(os.getpid()).memory_info().rss
 except Exception:return 0
def main():
 import torch
 OUT.mkdir(parents=True,exist_ok=True);print('PHASE3R START\nSATQUERY v1 ARCHITECTURE = S1 + S2 MULTIMODAL\nDATASET = BIGEARTHNET\nS1 = REQUIRED\nS2 = REQUIRED\nFUSION = CROMA JOINT\nS2 ONLY = BASELINE\nTEST ACCESS = 0\nJOINT PROJECTOR SHA = '+EXPECTED_JOINT_SHA,flush=True)
 man=json.loads(MANIFEST.read_text());rows=man['selection']['validation'];assert len(rows)==30 and Counter(r['task_type'] for r in rows)==Counter({'binary_qa':10,'multiple_choice_qa':10,'caption':10}) and man['test_access_count']==0
 capability={'primary_route':'MULTIMODAL_S1_S2','supported':['MULTIMODAL_BINARY','MULTIMODAL_MCQ','MULTIMODAL_CAPTION'],'required_modalities':['S1','S2'],'baseline':['S2_ONLY'],'research_only':['S1_ONLY'],'not_supported':['TEMPORAL_CHANGE','GROUNDING','UNVALIDATED_TASKS'],'test_access_count':0};dump('satquery_v1_capability_matrix.json',capability)
 s1=S1SARProjector().eval();s1.load_state_dict(torch.load(S1CK,map_location='cpu',weights_only=True)['state_dict']);s10=module_fingerprint(s1);s2=S2MultispectralProjector().eval();s2.load_state_dict(torch.load(S2CK,map_location='cpu',weights_only=True)['state_dict']);s20=module_fingerprint(s2)
 controller=SatQueryV1Controller();samples={x.patch_id:x for x in discover_samples(DATA,strict=True)};prepared={r['image_id']:load_sample(samples[r['image_id']]) for r in rows};first=prepared[rows[0]['image_id']]
 # Explicit failure tests before loading the normal route.
 base={'task_type':'caption','question':'describe','patch_id':first.patch_id,'s1_patch_id':first.patch_id,'s2_patch_id':first.patch_id,'spatial_metadata':first.metadata}
 failures={'missing_s1':controller.run_satquery(s1=None,s2=first.raw_optical,**base),'missing_s2':controller.run_satquery(s1=first.raw_sar,s2=None,**base),'mismatch':controller.run_satquery(s1=first.raw_sar,s2=first.raw_optical,**{**base,'s2_patch_id':'wrong'}),'bad_s1':controller.run_satquery(s1=np.zeros((1,120,120),np.float32),s2=first.raw_optical,**base),'bad_s2':controller.run_satquery(s1=first.raw_sar,s2=np.zeros((11,120,120),np.float32),**base),'nan':controller.run_satquery(s1=np.full((2,120,120),np.nan,np.float32),s2=first.raw_optical,**base)}
 started=time.perf_counter();torch.cuda.reset_peak_memory_stats();results=[]
 for i,r in enumerate(rows,1):
  p=prepared[r['image_id']];res=controller.run_satquery(task_type=r['task_type'],question=q(r),s1=p.raw_sar,s2=p.raw_optical,patch_id=p.patch_id,s1_patch_id=p.patch_id,s2_patch_id=p.patch_id,spatial_metadata=p.metadata);res['record_id']=r['record_id'];res['target']=a(r);res['correct']=res['parsed_answer']==a(r) if r['task_type']!='caption' else None;results.append(res);print(f'[3R][MULTIMODAL] record {i}/30',flush=True)
 elapsed=time.perf_counter()-started;peak_vram=torch.cuda.max_memory_allocated();peak_ram=ram();ok=[r for r in results if r['status']=='OK'];by=lambda t:[r for r in results if r['task_type']==t];binary=by('binary_qa');mcq=by('multiple_choice_qa');caption=by('caption');metrics={'binary':{'success':sum(r['status']=='OK' for r in binary),'parseability':sum(r['parsed_answer'] is not None for r in binary),'correct':sum(r['correct'] is True for r in binary)},'mcq':{'success':sum(r['status']=='OK' for r in mcq),'parseability':sum(r['parsed_answer'] is not None for r in mcq),'correct':sum(r['correct'] is True for r in mcq)},'caption':{'success':sum(r['status']=='OK' for r in caption),'nonempty':sum(bool(r['generated_response']) for r in caption),'unique_output_count':len({r['generated_response'] for r in caption})}}
 imm={**controller.unchanged(),'s1_projector':module_fingerprint(s1)==s10,'s2_projector':module_fingerprint(s2)==s20};failure_codes={k:v['error_code'] for k,v in failures.items()};model={'dataset':'BigEarthNet only','croma_mode':'CROMA_JOINT','joint_projector_sha256':EXPECTED_JOINT_SHA,'joint_projector_fingerprint':EXPECTED_JOINT_FINGERPRINT,'qwen_revision':controller.qwen_revision,'frozen':imm,'test_access_count':0};dump('satquery_v1_model_manifest.json',model);dump('satquery_v1_multimodal_validation_manifest.json',{'record_ids':[r['record_id'] for r in rows],'counts':dict(Counter(r['task_type'] for r in rows)),'test_access_count':0});dump('satquery_v1_multimodal_e2e_results.json',{'results':results,'metrics':metrics,'failure_tests':failure_codes,'test_access_count':0});dump('satquery_v1_resource_profile.json',{'total_seconds':elapsed,'mean_seconds_per_record':elapsed/30,'peak_vram_bytes':peak_vram,'peak_ram_bytes':peak_ram,'device':'cuda','test_access_count':0});limits={'paired_s1_s2_required':True,'fusion_effectiveness':'bounded fixed panel did not show clear improvement over S2-only','modality_identity_sensitivity':'generated decisions weakly sensitive','s2_only_baseline':'performed better on fixed Binary/MCQ panel','claims_prohibited':['SOTA','benchmark superiority','generalization','fusion accuracy gain'],'test_access_count':0};dump('satquery_v1_limitations.json',limits);summary={'status':'SATQUERY_V1_MULTIMODAL_READY_WITH_LIMITATIONS','primary_route':'MULTIMODAL_S1_S2','e2e_success':f'{len(ok)} / 30','metrics':metrics,'failure_tests':failure_codes,'s2_baseline_available':True,'immutability':imm,'test_access_count':0};dump('satquery_v1_summary.json',summary)
 print('QWEN REVISION = '+controller.qwen_revision+'\nMULTIMODAL E2E SUCCESS = '+summary['e2e_success']+'\nBINARY = '+str(metrics['binary'])+'\nMCQ = '+str(metrics['mcq'])+'\nCAPTION = '+str(metrics['caption'])+'\nMISSING S1 HANDLING = '+('PASS' if failure_codes['missing_s1']=='MISSING_S1_FOR_MULTIMODAL_ROUTE' else 'FAIL')+'\nMISSING S2 HANDLING = '+('PASS' if failure_codes['missing_s2']=='MISSING_S2_FOR_MULTIMODAL_ROUTE' else 'FAIL')+'\nMISMATCHED PAIR HANDLING = '+('PASS' if failure_codes['mismatch']=='MISMATCHED_PATCH_ID' else 'FAIL')+'\nS2 BASELINE AVAILABLE = YES\nQWEN UNCHANGED = '+('YES' if imm['qwen'] else 'NO')+'\nCROMA UNCHANGED = '+('YES' if imm['croma'] else 'NO')+'\nJOINT PROJECTOR UNCHANGED = '+('YES' if imm['joint_projector'] else 'NO')+'\nMEAN INFERENCE TIME = '+str(elapsed/30)+'\nPEAK VRAM = '+str(peak_vram)+'\nPEAK RAM = '+str(peak_ram)+'\nTEST ACCESS = 0\nSATQUERY v1 CLASSIFICATION = SATQUERY_V1_MULTIMODAL_READY_WITH_LIMITATIONS\nPHASE3R COMPLETE',flush=True)
if __name__=='__main__':main()
